Repository SolarLiner/bevy-kira-components, pull requests merged in 2024-05, with the labels that each got.

#7 refactor: rename consts from NUM_ prefix to _COUNT suffix
  src/diagnostics.rs
Labels: Feature

#8 fix: use linear attenuation in SpatialEmitter by default
  src/spatial.rs
Labels: Examples

#14 Add `AudioFileHandle::toggle` convenience method
  src/sources/audio_file/source.rs
Labels: Feature

#16 Remove `Result<(), E>` from the API
  Cargo.lock
  Cargo.toml
  examples/audio_control.rs
  examples/custom_sound/src/sine_wave.rs
  examples/interactive/src/main.rs
  examples/spatial/src/main.rs
  flake.lock
  flake.nix
  src/backend.rs
  src/sources/audio_file/mod.rs
  src/sources/audio_file/source.rs
  src/sources/mod.rs
  src/spatial.rs
Labels: Upstream, Breaking, Refactor

#17 Recreate `audio` and `decodable/custom_sound` examples from `bevy_audio`
  Cargo.lock
  Cargo.toml
  examples/audio.rs
  examples/custom_sound.rs
  examples/custom_sound/Cargo.toml
  examples/custom_sound/src/main.rs
  examples/custom_sound/src/sine_wave.rs
  src/sources/mod.rs
Labels: Examples
